### ISSUE TITLE
Tracking upload progress

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#15]
Currently, core does not expose a way to track the upload progress of a file, which prevents storj.js from emitting `on('data'` events and updating `file.progress`.

Things to think about:

* If a file is being uploaded across multiple shards concurrently, the order in which chunks of data are emitted via the `data` event may not match the order of those chunks in the file. What implications does this carry for userland?
* When do we emit a `data` event? When we finish encrypting the chunk, when we send the data over the wire, when we get confirmation that the farmer received that data, etc? What implications will the timing of the `data` event carry for userland?

**Comment by rockydd** [comment]
@retrohacker , When I upload a file whose size is about 8M, the browser will freeze for a long time. And the computer fan starts to spin very fast. Looks like it's doing a very heavy job. However, from the chrome development console, I see the transfer finished very quickly. But the freezing last for 30+ minutes. So what is it doing? Is this a bug?

**Comment by retrohacker** [comment]
Hey @rockydd, this is a known problem. Crypto is slow, and we are doing it on the main thread.

https://github.com/Storj/storj.js/milestone/1

Large file support is coming, but it involves tackling non-trivial problems.

**Comment by rockydd** [comment]
Thanks @retrohacker, so do we have an ETA for this issue?

**Comment by retrohacker** [comment]
Chrome suffers less, I'm a firefox user but have chromium set aside for Storj.js development during the beta. Things will get better :-)

**Comment by retrohacker** [comment]
No firm ETA, though I suspect each of those problems will be 2-6 weeks of sustained work to get through. We are also tackling SSL support to get you Storj.js on HTTPS pages. That project is scheduled first.

**Comment by retrohacker** [comment]
(HTTPS will also get you service workers which opens up a whole new world for dev)

**Comment by rockydd** [comment]
OK, got it. Thanks.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
