### ISSUE TITLE
Firefox de-optimizes Buffer.concat

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#34]
When streaming data from farmers, we use a _lot_ of Buffer.concat operations to buffer up the file into memory. Firefox appears to be de-optimizing this function. Since all of the crypto logic is shared with the rest of the browser's thread, the user experience for downloading a large file is that their browser locks up until the browser pauses the script with a prompt.

Firefox User Experience:
![snapshot1](https://cloud.githubusercontent.com/assets/1081565/23955182/926180de-096f-11e7-9d75-e8686a740d16.png)

Flamegraph:
![snapshot1](https://cloud.githubusercontent.com/assets/1081565/23955245/bff98e10-096f-11e7-9d24-40f5d4e08e9a.png)

You can see `concat` invocations (and descendant functions) are plateaus.

Function breakout:
![snapshot1](https://cloud.githubusercontent.com/assets/1081565/23955449/457b4592-0970-11e7-8c2a-f32df3b0a036.png)

Concat is the in call chain of >75% of the on-thread time for our script

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
