### ISSUE TITLE
Storj.js blocks webpage

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#35]
Storj.js is CPU heavy compared to most JS on the web. This creates a less-than-ideal user experience in many browsers.

The solution is [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers), but we need a little more exploration before we jump to an implementation.

Constraints:
* Multiple shards should be able to be decrypted simultaneously for the same file. (Web Worker pool)
* User shouldn't have to pass in a URL to their local `storj.js` script when initializing. (Should construct a blob via a string containing the JS, pull it's URL, and use that to initialize the Web Worker)
* Should implement a streaming interface.

**Comment by retrohacker** [comment]
Note that the effect of this is compounded by #36 and #34

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
