### ISSUE TITLE
Reduce size of final bundle

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#51]
The file sizes for `storj.es5.js` and `storj.es6.js` are both quite large (several MBs). We should pipe them through `uglify` or something similar to reduce their final size.

Note: we need to maintain our sourcemaps when doing the transform.

**Comment by retrohacker** [comment]
While it would be nice to get a minified bundle pushed out the door with the initial release, we need more testing before we can certify it works.

UglifyJS2 has an experimental branch for minifying our es6 bundle supporting 'harmony' flags.

The es5 bundle emits quite a few warnings.

I think the best path forward would be to extend testling to include tests for both the minified es5 and es6 bundles. This will be a time investment though and shouldn't block us from shipping.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
