### ISSUE TITLE
File API  methods should be safe to call before `ready`

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#60]
Since the methods that operate on the file are either stream or callback based, they should be safe to call before the file enters into a `ready` state.

Callback based functions should either callback with an error if the `file` object errors before `ready` is emitted, or should invoke their callback as soon as they have the data necessary to complete the request.

Stream based functions should return a stream immediately. The stream should error when `file` errors, and should provide data as soon as it becomes readable. **NOTE**: The stream emitting an error should not save a `file` object from throwing an `unhandled` error if the user does not register an `error` listener directly on the `file` object. In a similar manner, a readable stream coming from a `file` should _not_ block the `file` from downloading it's data from a farmer into a blob store. I.E. calling `createReadStream` and not consuming data from it should not fill the TCP socket's stream's internal buffer, data should still be able to flow into the underlying blob store. 

* `getBuffer`
* `getBlob`
* `getBlobUrl`
* `appendTo`
* `renderTo`
* `getReadStream`

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
