### ISSUE TITLE
Improve stack traces for tests

### ISSUE THREAD

**Issue by retrohacker** [Storj/storj.js#64]
Right now stack traces are super noisy in tests. Would be handy to have a source-map aware error object.

Look into:
* https://github.com/evanw/node-source-map-support
* https://www.npmjs.com/package/nyc#accurate-stack-traces-using-source-maps

**Comment by retrohacker** [comment]
Would also be handy if (for Node.js) stack traces would span the event loop. Look into:

* https://github.com/mattinsler/longjohn

For both browser and Node.js, would be handy if we didn't drop any context from the stack trace. Look into:

* `Error.stackTraceLimit=Infinity`

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
