### ISSUE TITLE
Update docs for `keypair.sign(message)`

### ISSUE THREAD

**Issue by barbaraliau** [Storj/storj.js#82]
Default when signing is `{ compact: true }`. I've found that this needs to be `{ compact: false }` in order to generate the correct signature.

Suggested change to lines 395-397 in README.md:

`var signature = keypair.sign(message, [opts])`
Sign a message with this key. `message` should be either a `String` or a `Buffer`, and the returned signature will be a `String`. Default options is `{ compact: true }`.

or

`var signature = keypair.sign(message, { compact: false })`
Sign a message with this key. `message` should be either a `String` or a `Buffer`, and the returned signature will be a `String`. Default options is `{ compact: true }`.

[Keypair Docs](https://github.com/Storj/bridge/blob/master/doc/auth.md)

```
KeyPair.prototype.sign = function(message, options) {
  var sign = null;
  var opts = merge({ compact: true }, options);

  if (opts.compact) {
    sign = Message(message).sign(this._privkey);
  } else {
    if (!Buffer.isBuffer(message)) {
      message = new Buffer(message, 'utf8');
    }

    sign = ecdsa.sign(
      crypto.createHash('sha256').update(message).digest('hex'),
      this.getPrivateKey()
    ).toDER('hex');
  }
```

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
